# Generated by Django 3.0.6 on 2020-06-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200617_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
