# Generated by Django 3.0.6 on 2020-06-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200618_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='email',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
