# Generated by Django 3.0.6 on 2020-06-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_addressbook_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='email',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
