# Generated by Django 3.0.6 on 2020-06-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200618_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
