# Generated by Django 3.0.6 on 2020-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_addressbook_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='favorite',
            field=models.BooleanField(default=True),
        ),
    ]
