# Generated by Django 3.0.6 on 2020-07-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_addressbook_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='owner',
        ),
    ]
